spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1399338968-32gud2psjs25hhp7j97bkre380i5rkc9.apps.googleusercontent.com
            client-secret: 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
